// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(TiendaDbContext))]
    partial class TiendaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Accesorios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad");

                    b.Property<string>("Nombre");

                    b.Property<int>("Precio");

                    b.HasKey("Id");

                    b.ToTable("accesorios");
                });

            modelBuilder.Entity("Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<int>("Cedula");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("Model.Compra_Accesorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccesoriosIDId");

                    b.Property<int>("Cantidad");

                    b.Property<int?>("ClienteIDId");

                    b.Property<int>("Total");

                    b.HasKey("Id");

                    b.HasIndex("AccesoriosIDId");

                    b.HasIndex("ClienteIDId");

                    b.ToTable("compra_Accesorios");
                });

            modelBuilder.Entity("Model.Compra_Consola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad");

                    b.Property<int?>("ClienteIDId");

                    b.Property<int?>("ConsolaIDId");

                    b.Property<int>("Total");

                    b.HasKey("Id");

                    b.HasIndex("ClienteIDId");

                    b.HasIndex("ConsolaIDId");

                    b.ToTable("compra_Consolas");
                });

            modelBuilder.Entity("Model.Compra_Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad");

                    b.Property<int?>("ClienteIDId");

                    b.Property<int?>("GamesIDId");

                    b.Property<int>("Total");

                    b.HasKey("Id");

                    b.HasIndex("ClienteIDId");

                    b.HasIndex("GamesIDId");

                    b.ToTable("compra_Games");
                });

            modelBuilder.Entity("Model.Consola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Modelo");

                    b.Property<int>("Precio");

                    b.Property<int>("Stock");

                    b.HasKey("Id");

                    b.ToTable("Consolas");
                });

            modelBuilder.Entity("Model.Games", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genero");

                    b.Property<int>("Precio");

                    b.Property<int>("Stock");

                    b.Property<string>("Titulo");

                    b.HasKey("Id");

                    b.ToTable("games");
                });

            modelBuilder.Entity("Model.Compra_Accesorio", b =>
                {
                    b.HasOne("Model.Accesorios", "AccesoriosID")
                        .WithMany()
                        .HasForeignKey("AccesoriosIDId");

                    b.HasOne("Model.Cliente", "ClienteID")
                        .WithMany()
                        .HasForeignKey("ClienteIDId");
                });

            modelBuilder.Entity("Model.Compra_Consola", b =>
                {
                    b.HasOne("Model.Cliente", "ClienteID")
                        .WithMany()
                        .HasForeignKey("ClienteIDId");

                    b.HasOne("Model.Consola", "ConsolaID")
                        .WithMany()
                        .HasForeignKey("ConsolaIDId");
                });

            modelBuilder.Entity("Model.Compra_Game", b =>
                {
                    b.HasOne("Model.Cliente", "ClienteID")
                        .WithMany()
                        .HasForeignKey("ClienteIDId");

                    b.HasOne("Model.Games", "GamesID")
                        .WithMany()
                        .HasForeignKey("GamesIDId");
                });
#pragma warning restore 612, 618
        }
    }
}
